# Proxmox Configuration
proxmox:
  host: "your-proxmox-host.local"  # Your Proxmox hostname or IP address
  port: 8006                       # Proxmox web interface port (default: 8006)
  verify_ssl: false                # Set to false for self-signed certificates
  api_token: ""                    # Your Proxmox API token (leave empty for security)
  
# LXC Container Defaults
lxc:
  template: "ubuntu-22.04-standard"
  memory: 1024
  cores: 1
  storage: "local-lvm"
  
# API Configuration
api:
  timeout: 30
  retries: 3

# Note: For security, do not commit your actual API token to version control
# You can either:
# 1. Set it when running the script
# 2. Use environment variables
# 3. Store it in a separate, gitignored config file
