version: '3.8'

services:
  webhook-server:
    build: .
    container_name: github-webhook-server
    ports:
      - "8080:8080"
    environment:
      - WEBHOOK_PORT=8080
      - WEBHOOK_LOG_FILE=/tmp/github_webhook.log
      - PYTHONUNBUFFERED=1
      # Uncomment and set these for notifications
      # - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      # - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      # - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    volumes:
      - webhook_logs:/tmp
      - ./scripts:/app/scripts:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - monitoring

  # Optional: Add a reverse proxy for HTTPS
  nginx:
    image: nginx:alpine
    container_name: webhook-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webhook-server
    restart: unless-stopped
    networks:
      - monitoring
    profiles:
      - proxy

  # Optional: Add monitoring dashboard
  dashboard:
    image: nginx:alpine
    container_name: monitoring-dashboard
    ports:
      - "3000:80"
    volumes:
      - ./monitoring:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - monitoring
    profiles:
      - dashboard

volumes:
  webhook_logs:
    driver: local

networks:
  monitoring:
    driver: bridge
